### Домашнее задание «Библиотека numpy. Вычислительные задачи»
А.Петряшев (DS-28)

In [56]:
import numpy as np

Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [5]:
n = 10

In [6]:
numpy_array = np.arange((n - 1), -1, -1)
numpy_array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [53]:
matrix_to_work = np.diag(numpy_array, k=0) 
matrix_to_work

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [54]:
totalsum = 0
j = -1
for i in matrix_to_work:
    j+=1
    totalsum += i[j]
print(totalsum)


45


In [98]:
n = 15

diag_matrix = np.diag(np.arange(n), k=0)
diag_matrix

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  6,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  7,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  8,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  9,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 11,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 12,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 13,  0],
       [ 0,  0,  0,  0,  0,  0,  0

In [103]:
sum_diag = sum(np.diagonal(diag_matrix, offset = 0))

print(sum_diag)

105


In [95]:
dm = np.arange(n).reshape(5, 3)
dm

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [106]:
sum_dm = sum(np.diagonal(dm, offset = -1))
sum_dm

21

Задание 3
Решите систему уравнений:

4x + 2y + z = 4

x + 3y = 12

5y + 4z = -3

In [8]:
from numpy import linalg

In [27]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [28]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [14]:
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [108]:
inv_a = np.linalg.inv(a) # обратная матрица из коэффициентов перед неизвестными
output = np.dot(inv_a, b) # скалярное произведение матрицы и вектора из свободных членов

print(output)


[ 0.46666667  3.84444444 -5.55555556]


Задача 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. Остальные столбцы - количество покупок категорий товаров этим пользователем.

На сайт заходит очередной посетитель, о покупках которого известно следующее:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя. Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats

In [25]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

In [29]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [66]:
def find_most_similar_user(users_stats, next_user_stats):
    
    closure = {}
    next_user_stats_length = np.linalg.norm( next_user_stats )
    
    for user_id, user_stat in enumerate(users_stats):
    
        user_stat_length  = np.linalg.norm( user_stat )
        user_closure = np.dot( user_stat, next_user_stats ) / ( user_stat_length * next_user_stats_length )
        closure[user_id] = user_closure
        closure_dict.append( {user_id : user_closure})
        
        max_closure = max(closure.values())
        
    for user, closure in closure.items():
        if closure == max_closure:
            print(f'Самый похожий пользователь user id: {user}. Индекс похожести: {round(closure, 3)} ')
    else: pass



In [67]:
find_most_similar_user(users_stats, next_user_stats)

Самый похожий пользователь user id: 7. Индекс похожести: 0.949 
